### ISSUE TITLE
Hello i think im having some issues with this plugin

### ISSUE THREAD

**Issue by Paradis4432** [EverNife/EverNifeCore#2]
i have been noticing some memory leaks, after making some tests and heap summary i found this
![Screenshot_98](https://github.com/EverNife/EverNifeCore/assets/49301263/1093f58f-282a-45aa-97c0-dc06a6f1ca7c)
![image](https://github.com/EverNife/EverNifeCore/assets/49301263/e70c8405-7c30-41ec-ba82-ecb45cf72d92)

running arclight 1.16.5 forge pixelmon with 90 players online

**Comment by EverNife** [comment]
Sure, i will talk with you on discord!

I will update this issue with our conclusions later.

**Comment by EverNife** [comment]
Sumarry for now:

The "**memory leak**" is created "by design". This plugin prioritizes CPU over MEMORY.

The current server has 17.000 Unique Players. That is lot.
With all those 17k Unique players my plugin is using +- 500mb of memory.

I will try to crate some possible solutions for servers like this.

[1] Forget about CPU over Memory, and remove the CACHE of config files completly.

[2] Finish the DormantSystem, where only PlayerData that joined in the last X days will be loaded on memory.

[3] A third option is to cache the config file only after it was used, so, rather than cache it on server load, it will cache by demand of usage.

**I will probably make a mix of 2 and 3.**

**Comment by EverNife** [comment]
After some talk with the SimpleYaml's dev here https://github.com/Carleslc/Simple-YAML/issues/80, the problem was not on Simple-YAML but it was a natural overhead of snakeyaml itself.

So, there was no way to keep things on the same way without this overhead.

With that in mind i opted for a InMemory String cache after some time of no use. The result was the bellow.


![image](https://github.com/user-attachments/assets/24585723-40c8-4c9a-ac56-1d4eded08c95)

This update will be present on the next release soon.
